#!/usr/bin/env bash
# Run on VPS (after git clone): bash deploy/vps-bootstrap.sh
# Creates backend/.env, starts Docker stack, prints credentials once.

set -euo pipefail

REPO="${HOME}/happy-feet-travellers"
BACKEND="${REPO}/backend"
SECRETS_FILE="${BACKEND}/.deploy-secrets.txt"
CORS_ORIGINS="${CORS_ORIGINS:-https://happy-feet-travellers-frontend.vercel.app}"

if [[ ! -d "${BACKEND}" ]]; then
  echo "Missing ${BACKEND}. Clone the repo first:"
  echo "  git clone https://github.com/moladen/happy-feet-travellers.git"
  exit 1
fi

cd "${BACKEND}"

if ! command -v docker >/dev/null 2>&1; then
  echo "Installing Docker..."
  sudo apt-get update -qq
  sudo apt-get install -y docker.io docker-compose-plugin
  sudo usermod -aG docker "${USER}" || true
  echo "Docker installed. If 'docker' fails, log out and SSH in again, then re-run this script."
fi

if ! docker info >/dev/null 2>&1; then
  echo "Cannot run docker (permission?). Try: sudo usermod -aG docker \$USER && newgrp docker"
  echo "Or run: sudo docker compose ..."
  DOCKER="sudo docker"
else
  DOCKER="docker"
fi

JWT_SECRET="$(openssl rand -base64 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"
ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | head -c 18)"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@happyfeet.com}"

cat > .env <<EOF
# Generated by deploy/vps-bootstrap.sh — $(date -Iseconds)
POSTGRES_USER=happy_feet
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=happy_feet
POSTGRES_PORT=5434

API_PORT=5000
NODE_ENV=production

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=7d

ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

CORS_ORIGINS=${CORS_ORIGINS}

RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=200

RUN_MIGRATIONS=true
RUN_SEED=true

ENQUIRY_NOTIFY_EMAIL=info@happyfeet.com
MAIL_FROM="Happy Feet Travellers <noreply@happyfeet.com>"
SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
SMTP_VERIFY_ON_START=false
EOF

chmod 600 .env

cat > "${SECRETS_FILE}" <<EOF
# Save these somewhere safe, then: rm ${SECRETS_FILE}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
EOF
chmod 600 "${SECRETS_FILE}"

echo "==> Building and starting API + Postgres..."
${DOCKER} compose up --build -d

echo "==> Waiting for health..."
for i in $(seq 1 30); do
  if curl -sf http://127.0.0.1:5000/api/health >/dev/null 2>&1; then
    echo "API is healthy."
    curl -s http://127.0.0.1:5000/api/health | head -c 200
    echo ""
    break
  fi
  sleep 2
  if [[ "$i" -eq 30 ]]; then
    echo "Health check timed out. Logs:"
    ${DOCKER} compose logs api --tail 40
    exit 1
  fi
done

echo ""
echo "=============================================="
echo " SAVE THESE (admin login + DB password):"
cat "${SECRETS_FILE}"
echo "=============================================="
echo ""
echo "Next steps:"
echo "  1. Vercel env: NEXT_PUBLIC_API_URL=http://103.22.140.216:5000/api (or https://api.YOUR_DOMAIN/api)"
echo "  2. Redeploy Vercel"
echo "  3. After first success, set RUN_SEED=false in backend/.env and: docker compose restart api"
echo "  4. Optional: sudo ufw allow 5000/tcp"
echo ""
echo "Public health test (from your Mac):"
echo "  curl http://103.22.140.216:5000/api/health"
