import { resolveTourPriceAmount } from '@/lib/tourPrice';
import { buildReserveSeatHref, isGroupDepartureTour } from '@/lib/tourReserve';

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function nl2br(s) {
  return esc(s).replace(/\n/g, '<br/>');
}

/**
 * Opens a print-friendly window (user can Save as PDF) with itinerary, policies summary, bank details & booking QR.
 */
export function openTourItineraryPrint(tour) {
  if (typeof window === 'undefined') return;

  const bookingUrl = isGroupDepartureTour(tour)
    ? buildReserveSeatHref(tour)
    : `https://wa.me/919876543210?text=${encodeURIComponent(`Booking / enquiry: ${tour.title} (${tour.date || ''})`)}`;
  const qrSrc = `https://api.qrserver.com/v1/create-qr-code/?size=140x140&data=${encodeURIComponent(bookingUrl)}`;

  const itineraryRows = (tour.itinerary || [])
    .map(
      (row) =>
        `<tr><td style="padding:8px;border:1px solid #ccc;vertical-align:top;width:22%"><strong>${esc(row.day)}</strong></td><td style="padding:8px;border:1px solid #ccc"><strong>${esc(row.title)}</strong><br/><span style="color:#333">${nl2br(row.details)}</span></td></tr>`
    )
    .join('');

  const incl = (tour.inclusions || []).map((x) => `<li>${esc(x)}</li>`).join('');
  const excl = (tour.exclusions || []).map((x) => `<li>${esc(x)}</li>`).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>${esc(tour.title)} — Itinerary</title>
  <style>
    body { font-family: Segoe UI, Arial, sans-serif; color: #1a1a1a; max-width: 800px; margin: 24px auto; padding: 0 16px; }
    h1 { color: #1F4E79; font-size: 22px; }
    .meta { margin: 12px 0 20px; font-size: 14px; color: #333; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 24px; }
    .grid { display: flex; gap: 24px; flex-wrap: wrap; margin: 24px 0; }
    .box { flex: 1; min-width: 200px; border: 1px solid #dceaf7; padding: 12px; border-radius: 8px; background: #f8fbff; }
    .bank { white-space: pre-wrap; font-size: 12px; font-family: Consolas, monospace; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <h1>${esc(tour.title)}</h1>
  <div class="meta">
    <div><strong>Dates:</strong> ${esc(tour.date || tour.startDate || '')}</div>
    <div><strong>Duration:</strong> ${esc(tour.duration)}</div>
    ${tour.departureCity ? `<div><strong>Departure city:</strong> ${esc(tour.departureCity)}</div>` : ''}
    <div><strong>Price:</strong> ${tour.category === 'customized' ? 'Starting from ' : ''}₹${resolveTourPriceAmount(tour.startingPrice, tour.price).toLocaleString('en-IN')} ${tour.category === 'customized' ? '(contact to customise)' : 'per traveller'}</div>
  </div>
  <h2 style="color:#1F4E79;font-size:16px">Day-wise itinerary</h2>
  <table><tbody>${itineraryRows}</tbody></table>
  <h2 style="color:#1F4E79;font-size:16px">Inclusions</h2>
  <ul>${incl}</ul>
  <h2 style="color:#1F4E79;font-size:16px">Exclusions</h2>
  <ul>${excl}</ul>
  <div class="grid">
    <div class="box">
      <strong>Scan to enquire / book</strong><br/>
      <img src="${qrSrc}" alt="Booking QR" width="140" height="140" style="margin-top:8px"/>
    </div>
    <div class="box">
      <strong>Bank details</strong>
      <div class="bank">${nl2br(tour.bankDetails || 'Payment details shared on confirmed booking.')}</div>
    </div>
  </div>
  <p style="font-size:11px;color:#555">Generated by Happy Feet Travellers. Carry a printout or PDF on trip day. Terms & cancellation as per brochure / quotation.</p>
  <script>window.onload=function(){window.print();}</script>
</body>
</html>`;

  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
}
